spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

---
spring:
  application:
    name: board-local
  config:
    activate:
      on-profile: local


---
spring:
  application:
    name: board-dev
  config:
    activate:
      on-profile: dev

---
spring:
  application:
    name: board-prod
  config:
    activate:
      on-profile: prod