spring:
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: cloudlibrary/rds/board/mysql
      driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
      username: cloudlibrary/rds/board/mysql

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update


feign:
  client:
    config:
      default:
        connectTimeout: 100
        readTimeout: 1000
        loggerLevel: BASIC

---
spring:
  application:
    name: board-local
  config:
    activate:
      on-profile: local


---
spring:
  application:
    name: board-dev
  config:
    activate:
      on-profile: dev

---
spring:
  application:
    name: board-prod
  config:
    activate:
      on-profile: prod